# Generated by Django 5.0.4 on 2024-04-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1023)),
                ('content', models.CharField(default='', max_length=65535)),
                ('last_updated', models.DateTimeField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
